# Generated by Django 5.1.6 on 2025-02-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('telefone', models.BigIntegerField(verbose_name='telefone')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
            ],
        ),
    ]
