# Generated by Django 5.1.6 on 2025-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(max_length=30, verbose_name='a')),
                ('b', models.IntegerField(max_length=30, verbose_name='b')),
                ('c', models.IntegerField(max_length=30, verbose_name='c')),
            ],
        ),
    ]
